# Generated by Django 5.2.5 on 2025-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts', models.TextField(help_text='list of subdomains/domains that will replace as host parametr in vless config (one subdomain/domain per line)')),
                ('path', models.CharField(help_text='subdomain/domain for path parametr in vless config', max_length=255)),
                ('sni', models.CharField(help_text='subdomain/domain for SNI paramets in vless config', max_length=255)),
                ('port', models.PositiveIntegerField(default=2053, help_text='service port (default : 2053)')),
                ('inbound', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Config',
                'verbose_name_plural': 'Global Configs',
            },
        ),
    ]
