# Generated by Django 5.2.5 on 2025-08-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2rayconfigcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_address', models.CharField(max_length=100)),
                ('panel_port', models.IntegerField()),
                ('panel_username', models.CharField(max_length=100)),
                ('panel_password', models.CharField(max_length=100)),
                ('x_ui_listen_port', models.IntegerField()),
                ('inbound_id', models.IntegerField()),
            ],
        ),
    ]
