# Generated by Django 5.2.5 on 2025-09-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermetadata_created_at_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
