# Generated by Django 5.2.5 on 2025-08-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(help_text='نام پلن', max_length=150)),
                ('number_of_users', models.PositiveIntegerField(help_text='تعداد کاربران کانفیگ')),
                ('time', models.PositiveIntegerField(help_text='مدت زمان کانفیگ بر حسب ماه')),
                ('usage', models.PositiveIntegerField(help_text='حجم کانفیگ بر حسب گیگابایت')),
                ('price', models.PositiveIntegerField(help_text='قیمت کانفیگ بر حسب کوین (هر کوین هزار تومن)')),
            ],
        ),
    ]
